### ISSUE TITLE
[UX] Task page for authenticated users

### ISSUE THREAD

**Issue by getjump** [klenin/cats-main#32]
User expierence improvance for task page that can be seen by authenticated users
- Storing last user selected compiler on uploading task solve (as i promised i will implement this by myself)
- ~~Select task by double click on it's row (it's really hard to reach radio button of that size)~~
- Will be nice if we have ability to upload task solve from other places (at least way to main system from task-view page, task page for contest for ex.)
- Drag-and-Drop?

**Comment by klenin** [comment]
>Will be nice if we have ability to upload task solve from other places
>(at least way to main system from task-view page
I think you mean a link from the problem text to the contest problem list.
This is slightly problematic because problem text is cached as a static html,
intended to be ready for independend usage.
For this reason problem text does not have any UI. I guess we could display in an iframe,
but I dislike iframes in general. Perhaps link could be added by Javascrips, similar to "spaces" button.

>task page for contest for ex.
I do not understand this.

**Comment by getjump** [comment]
> This is slightly problematic because problem text is cached as a static html,
intended to be ready for independend usage.

Probably the best way, is to modify DOM of children window from a parent window (add link to last page from parent).

> task page for contest for ex.
I do not understand this.

I meant, page where are located list of tasks for current contest(and or page with some run)

**Comment by klenin** [comment]
There is now a link from problem text to problem list.
As for drag-and-drop, it is working by default as a standard browser feature.
