### ISSUE TITLE
[UX] Global

### ISSUE THREAD

**Issue by getjump** [klenin/cats-main#37]
User expierence improvance regarding whole system

* Move everything to AJAX isn't bad idea, [jquery-pjax](https://github.com/defunkt/jquery-pjax) is probably best way
* We shouldn't display any system information, an example "Access Prohibited", "Incorrect.." blah blah, as like responses with error code 500, that definitely helps attacker detect system breaches
* Is json option in some places realy needed? If it realy needed, we should change src keys, so they will not equal keys in database, and return same information, that could be fetched from page if it was html
* As for now current contest doesn't saves(if you logout and them log-in you will be selected Archive contest)(isn't it?), why doesn't save it?

**Comment by klenin** [comment]
>Move everything to AJAX
Extracted to issue #47

>We shouldn't display any system information, an example "Access Prohibited", "Incorrect.."
Yes, we should not. Currently, the only thing a user ever sees in case of any system failure is http code 500.
If you find a case where it is not so, please report.

>Is json option in some places realy needed?
Yes. See e.g. https://github.com/aelz/CourseWork

>return same information, that could be fetched from page if it was html
JSON API supplies a limited subset of data compared to full UI.
This is intentional, at least for now.

>current contest doesn't saves
Extracted
