### ISSUE TITLE
Code viewer: unused button or a bug?

### ISSUE THREAD

**Issue by BlackDoomer** [klenin/cats-main#91]
There is a button in the solution code viewer, placed nearly from the top right corner, with "?" char as a caption. This button looks so strange - when I press it, CATS pushes me a little window with the single "@ABOUT@" string in.
Is this button a something like unused feature of implemented code viewer control? Or this is a localization bug?

**Comment by klenin** [comment]
This is an artifact of using synhighlighter without a local config.
You are welcome to supply a config patch.
However, since the recent merge of server-side editor,
the plan is to migrate to some web editor with highlighter capabilities, perhaps ACE.

**Comment by cher-nov** [comment]
AFAIK, this happened because SyntaxHiglighter was improperly installed or something like that.
Watch this: [shCore.js#L88](https://github.com/alexgorbatchev/syntaxhighlighter/blob/b7154ce7a83aa091d53d8f9e662fcf955f0c31d9/scripts/shCore.js#L88)

It also seems that we can fix this by adding something like that, to the [syntax_highlight.tti](https://github.com/klenin/cats-main/blob/master/tt/includes/syntax_highlight.tti):
```javascript
SyntaxHighlighter.config.strings.aboutDialog = "<!--#include virtual="/about.html"-->";
```
Of course, `about.html` must also be placed into CATS repo.
Version of this file from SyntaxHighlighter version used can be obtained here: [about.html](https://github.com/alexgorbatchev/syntaxhighlighter/blob/b7154ce7a83aa091d53d8f9e662fcf955f0c31d9/build/includes/about.html).

Do we need such a patch?
